fingertip mk1.1 added for testing
icub-tech-iit/test-skin-patches pull request #18
Opened 2023-06-05 13:05 UTC by simeonedussoni

Added:
- skingui conf for the mk1.1 fingertip
- device lines in yarpmanager
- conf files for yarprobotinterface for use w/ MC4+ board

all teted and working with the `Superbuilid` and using the instructions here

2023-06-05 13:18 UTC, pattacini requested changes
I've one major request for change.
Then, I think @davidetome is a better fit as a reviewer.

@davidetome, let's remember to regenerate the docker image once merged.

2023-06-06 07:42 UTC, simeonedussoni commented on test-skin-mc4plus/config-files/skin-fingertip.xml
actually the file skin-fingertip.xml is a brand new created for testing the mk1.1 fingertips.

2023-06-06 07:45 UTC, pattacini commented on test-skin-mc4plus/config-files/skin-fingertip.xml
Ok! I thought the comment referred to the file [test-skin-mc4plus/config-files/applications/skin.xml](https://github.com/icub-tech-iit/test-skin-patches/pull/18/files/52464171d7559271bbd93e6bf74ab15fec4ea157#diff-6699960019c40cf4d4db37a11f7561d162fbc0e4a867972bb23cb2311ee21d96) for which I dropped my suggestion.

2023-06-06 11:18 UTC, simeonedussoni commented on test-skin-mc4plus/config-files/applications/skin.xml
now there is a dedicated app for the fingertip testing, with the naming coherent to the configuration file i.e. with the `V2_2` suffix. 
In this way it will be straightforward to add another one for the 3DMID device.

2023-06-06 11:21 UTC, pattacini commented on test-skin-mc4plus/config-files/applications/skin.xml
Ok, great 👍🏻 
But now we need to revert skin.xml to its previous state.

2023-06-06 12:40 UTC, pattacini commented on test-skin-mc4plus/config-files/applications/skin.xml
Thanks!

2023-06-06 12:40 UTC, pattacini approved these changes
The PR is fine with me now 👍🏻 
Awaiting @davidetome's final approval before merging.

2023-06-06 13:40 UTC, davidetome approved these changes

2023-06-06 13:40 UTC, merged